FROM ubuntu:latest

LABEL org.opencontainers.image.source=https://github.com/caffeinatedtoad/discord-bots
LABEL org.opencontainers.image.description="Marcus ARM Base"

RUN apt-get -y update
RUN apt install -y wget

RUN wget https://go.dev/dl/go1.24.4.linux-arm64.tar.gz
RUN tar -C /usr/local -xzf go1.24.4.linux-arm64.tar.gz

RUN apt-get install -y ffmpeg
RUN apt-get install -y build-essential

# This assumes a recent ubuntu version
RUN apt-get install -y opus-tools
RUN apt-get install -y pkg-config
RUN apt-get install -y libopus-dev
